kind: List
apiVersion: v1
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: app
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: app-docker
  spec:
    strategy:
      type: Docker
    source:
      type: Docker
      binary:
        asFile: all.jar
    output:
      to:
        kind: ImageStreamTag
        name: app:latest
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: app
  spec:
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          podTemplate(label: "java-mvn",
                      cloud: "openshift",
                      inheritFrom: "maven",
                      containers: [
              containerTemplate(name: "jnlp",
                                image: "openshift/jenkins-slave-maven-centos7:v3.9",
                                resourceRequestMemory: "256Mi",
                                resourceLimitMemory: "712Mi",
                                envVars: [
                envVar(key: "CONTAINER_HEAP_PERCENT", value: "0.25")
              ])
            ]) {
            node("java-mvn") {
              sh """
                  git clone https://github.com/drimailorr/emirates.git .
                  ./mvnw -Pprod clean verify
                  oc start-build --wait --follow -F app-docker --from-file=target/umsl-0.0.1-SNAPSHOT.jar
              """
            }
          }
    triggers:
    - type: ConfigChange


