kind: List
apiVersion: v1
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: app
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: app-docker
  spec:
    strategy:
      type: Docker
    source:
      type: Docker
      binary:
        asFile: all.jar
    output:
      to:
        kind: ImageStreamTag
        name: app:latest
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: app
  spec:
    source:
      git: 
        uri: https://github.com/drimailorr/emirates.git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy: 
        jenkinsfilePath: Jenkinsfile
    triggers:
    - type: ConfigChange


